# This is a basic workflow to help you get started with Actions

name: Flutter Web deploy on GH-Pages

# Controls when the action will run.
on:
  # Triggers the workflow on push  but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    name: Build Flutter web and Deploy
    env:
      secret_token: ${{secrets.commit_token}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - id: commit
        uses: pr-mpt/actions-commit-hash@v1

      - name: Install Dependencies
        run: flutter pub get

      - name: Generate a release build for Web
        run: flutter build web --base-href /silly_portfolio_flutter/

      - name: Git commands to push `build/web` folder to branch gh-pages
        run: |
          cd ./build/web
          git init
          git config --local user.email "csunshakya@gmail.com"
          git config --local user.name "ShakyaCsun's GitHub Action"
          git remote add origin https://${{secrets.commit_token}}@github.com/ShakyaCsun/silly_portfolio_flutter.git
          git checkout -b gh-pages
          git add .
          git commit -m "New update: ${{ steps.commit.outputs.short }}"
          git push origin gh-pages -f
